Service Worker Merged
vtex-apps/store pull request #513
Opened 2021-03-22 20:23 UTC by ariangc

Added support for Merged Service Worker

#### What problem is this solving?

This PR adds support for the new scheme of Service Workers used in the Store app. It allows the usage of more than one Service Worker within a scope, using the feature implemented on [service-worker-graphql](https://github.com/vtex/service-worker-graphql/blob/feat/working-sw/node/middlewares/getMergedSW.ts#L102)

#### How to test it?

Once store is fully charged, check if a Service Worker called `serviceWorkerMerged.js` is successfully registered on the main scope of the page.

Workspace: ariangc

#### Screenshots or example usage:

![image](https://user-images.githubusercontent.com/21017429/112053244-1ad13800-8b22-11eb-8e3c-7fba9b40cbd1.png)

#### Related to / Depends on

- [service-worker-graphql](https://github.com/vtex/service-worker-graphql/)
- [onesignal](https://github.com/vtex-apps/onesignal)
- [pwa-graphql](https://github.com/vtex/pwa-graphql)

#### How does this PR make you feel? [:link:](http://giphy.com/)

![](https://media.giphy.com/media/JfSB6Bbyq5AaJc7xZE/giphy.gif)

2021-03-22 20:56 UTC, klzns requested changes
Missing changelog entry, see comment: https://github.com/vtex-apps/store/pull/513#issuecomment-804369817

2021-03-25 12:47 UTC, klzns requested changes

2021-03-25 12:47 UTC, klzns commented on CHANGELOG.md
> +- Service Worker Merged implementation adapted.
Missing changelog header

```suggestion
### Changed
- Use the new service-worker-graphql endpoint.
```

2021-03-26 16:48 UTC, victorhmp requested changes

2021-03-26 16:48 UTC, victorhmp commented on react/StoreWrapper.js
> +            src: `${rootPath}/serviceWorkerRegister.js${queryMatch}${
We should probably change this route, so that it's not in the website's root.
Something like `/service-worker/register.js`

2021-04-05 19:16 UTC, victorhmp approved these changes

2021-04-05 19:30 UTC, merged