Update Crowdin file
vtex-apps/store pull request #535
Opened 2021-08-24 09:27 UTC by daniserejo

#### What problem is this solving?

Update Crowdin file for crowdin integration

2021-08-24 14:21 UTC, camilavcoutinho requested changes

2021-08-24 14:21 UTC, camilavcoutinho commented on CHANGELOG.md
> +- `crowdin.yml` for crowdin integration
```suggestion
- Crowdin.yml for crowdin integration 
```

2021-08-24 16:48 UTC, camilavcoutinho approved these changes

2021-09-08 12:34 UTC, camilavcoutinho approved these changes

2021-09-08 13:13 UTC, igorbrasileiro approved these changes

2021-09-08 13:13 UTC, igorbrasileiro commented on CHANGELOG.md
> +
```suggestion
```

2021-09-08 13:13 UTC, igorbrasileiro commented
Remove changelog changes and merge.

2021-09-08 16:56 UTC, merged