fix: ADD location.search  in url redirect on ProfileChallenge
vtex-apps/store pull request #578
Opened 2023-04-11 18:08 UTC by davipguimaraes

#### What problem is this solving?

When mount url to redirect from login, the method getLocation ignore url parameters and lost parameters.
This problem it's commum in page with URI like: `/checkout/orderplaced?og=09876543210978`

2023-04-20 14:30 UTC, filipewl requested changes
Hey @davipguimaraes! Thank you for your contribution.

Could you please share a workspace link where we can reproduce the reported behavior?

In the meantime, I left some suggestions. There's a lint error that should be easy to take care of.

2023-04-20 14:30 UTC, filipewl commented on CHANGELOG.md
> +- ADD `location.search` in url redirect on `ProfileChallenge`
Here's the expected format for this:
```suggestion

### Added
- `location.search` in URL redirect on `ProfileChallenge`

```

2023-04-20 14:30 UTC, filipewl commented on react/ProfileChallenge.tsx
> +
It's better not to include this unrelated change.
```suggestion
```

2023-04-20 14:59 UTC, filipewl approved these changes

2023-04-20 15:41 UTC, filipewl commented
Hey, @davipguimaraes! I'm planning to deploy this on Monday.

2023-04-20 19:11 UTC, davipguimaraes commented
Great news, I appreciate your changes.

2023-04-24 17:39 UTC, filipewl commented on CHANGELOG.md
> +- `location.search` in URL redirect on `ProfileChallenge`
```suggestion
### Fixed
- `ProfileChallenge` URL redirect not preserving the query params (`location.search`)
```

2023-04-24 17:42 UTC, merged

2023-04-24 18:17 UTC, filipewl commented
Hey @davipguimaraes! I've just deployed these changes as `vtex.store@2.131.1`. The update to this version should be automatic in the next few minutes. Thanks again.